version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --template-file pipeline.yaml --s3-bucket microservice-serverless-deploy --output-template-file sam-lambda-packaged.yaml
artifacts:
  files:
    - sam-lambda-packaged.yaml
